# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: A Programmer
subtitle:
description:
author: Wislay
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wislay.com/
root: /
permalink: articles/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
plugins:
  - hexo-generator-cname
  - hexo-generator-feed
  - hexo-generator-sitemap

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:/liaoaoyang/liaoaoyang.github.io.git
  branch: master

# Social
social:
  Homepage: /
  Weibo: http://weibo.com/wislay/
  GitHub: https://github.com/liaoaoyang/

# Etc
#avatar: https://avatars0.githubusercontent.com/u/9161676?v=3&s=460
avatar: https://blog.wislay.com/wp-content/uploads/2017/03/hippo.jpeg

menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories
  about: /about
  rss: /atom.xml
  sitemap: /sitemap.xml

highlight_theme: night
fancybox: true
icp: 
